### ISSUE TITLE
Document why hostNetwork is set to true on Chart

### ISSUE THREAD

**Issue by daniel-anova** [kubereboot/charts#24]
The setting `hostNetwork` has been added to the helm chart and set to `true` by default.

This setting limits usable hostPorts and will cause deployment to fail in several situations, and is not present in the [default deployment manifest](https://github.com/kubereboot/kured/blob/main/kured-ds.yaml) in the kured repository.

The PR #16 has no context for the change nor does the documentation.

Please add some documentation on why `hostNetwork: true` was set for the kured chart.

**Comment by joris-weijters** [comment]
Furthermore changing the `hostNework` by default to `true` changes the behaviour of the DNS for the pods. 
The `dnsPolicy` defaults to `ClusterFirst` but if `hostNetwork` is set to `true`, the `dnsPolicy` reverts to `Default` 
see: https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy.

This can cause different DNS behaviour, breaking the working of kured.

**Comment by jackfrancis** [comment]
@timo-42 would you be able to add some chart documentation to describe why or why not a user would want to use `hostNetwork: true`?

**Comment by jfklingler** [comment]
For more context on why some people are wondering why this was added and defaulted to true, it breaks things when there's something else running on 8080, an incredibly common non-privileged HTTP port.

**Comment by ckotzbauer** [comment]
I tested kured yesterday in my home-cluster without hostNetwork and it worked, so I think we can do a major chart-release with switched default (and a new parameter to preserve the current behaviour)
