### ISSUE TITLE
Make the nodeSelector.kubernetes.io/os default value linux

### ISSUE THREAD

**Issue by Koteko** [kubereboot/charts#34]
As kured only runs on Linux based nodes, would it make sense to add nodeSelector.kubernetes.io/os: linux to values.yaml. as a default value?
Otherwise, the helm chart tries to pull a kured docker image on a windows node and is constantly failing.

**Comment by ckotzbauer** [comment]
Thanks for the feedback, we added this to the newest chart-release.
