### ISSUE TITLE
Adopt artifactshub entry

### ISSUE THREAD

**Issue by mrad-bilel** [kubereboot/charts#5]
Hello,

I'm trying to add kured helm repo but the chart repository is not valid 

helm repo add kured  https://weaveworks.github.io/kured
Error: looks like "https://weaveworks.github.io/kured" is not a valid chart repository or cannot be reached: failed to fetch https://weaveworks.github.io/kured/index.yaml : 404 Not Found

I'm i using a wrong repo ?

**Comment by rahmme** [comment]
The [index.yaml](https://kubereboot.github.io/kured/index.yaml) in the new repo still contains references to the old repo.

**Comment by ckotzbauer** [comment]
I posted a message to the artifact-hub slack channel, describing our problem. I saw requests from others which had the same problem and they got it solved with help from the artifacthub-team.

**Comment by ckotzbauer** [comment]
We claimed the ownership. The page also has automatically updated to our latest changes: https://artifacthub.io/packages/helm/kured/kured
