### ISSUE TITLE
Inconsistencies found for sentinel related parameters

### ISSUE THREAD

**Issue by tmsdce** [kubereboot/charts#69]
Hello,

I noticed some inconsistencies in some parameters related to the sentinel feature.

1. Manifests (and README) uses `useRebootSentinelHostPath` while it is defined as `.configuration.useRebootSentinelHostPath` in the default `values.yaml` file. This needs to be aligned.
2. `.configuration.rebootSentinel` is unset by default while it states [that the default value is `/var/run/reboot-required`](https://github.com/kubereboot/charts/blob/f55c5ff0514e259e8a4653ecf18c1ca19e601c4b/charts/kured/values.yaml#L49C1-L49C123). This is indeed true in kured code, but should also be set accordingly in `values.yaml`. This is important because now that the `useRebootSentinelHostPath` param is set to `true` by default (at least when 1 is fixed`), you end up with a hostpath volume defined in your daemonset pointing to current directory like so :
```
      volumes:
        - name: sentinel
          hostPath:
            path: .
            type: Directory
```
The `path` in the ds template is using `path: {{ dir .Values.configuration.rebootSentinel }}` and as the `rebootSentinel` is empty by default, this results in the `dir` function returning `.`. This will obviously not work.

I'm also wondering if setting `useRebootSentinelHostPath` to true should be the default.

**Comment by tmsdce** [comment]
Thanks for your quick reply and the PR @ckotzbauer
These issues were all raised during testing before deploying on prod environments, so no harm done on our side :wink:

**Comment by ckotzbauer** [comment]
We also tested it, but maybe some last changes went wrong :laughing:
