### ISSUE TITLE
Make kured run on control-plane with taint

### ISSUE THREAD

**Issue by Brice187** [kubereboot/charts#82]
Currently this is only explained in the FAQ: https://kured.dev/docs/faq/

As a workaround I added a kustomize file to patch the daemonset, would be nice if I just had to set the reboot flag in the helm chart

**Comment by ckotzbauer** [comment]
Hi @Brice187,
I don't get the point. You can add a toleration with a kustomize-file when you do a yaml-based deployment. For the helm-chart you can define custom tolerations in the chart.
What do you mean with setting the reboot-flag in the helm-chart? The chart can't detect custom taints on your control-plane.
