### ISSUE TITLE
Bug: Unnecessary permissions

### ISSUE THREAD

**Issue by Yseona** [kubereboot/charts#86]
Hi community!

I just found that the [Daemonsets kured](https://github.com/kubereboot/charts/blob/main/charts/kured/templates/daemonset.yaml) in the charts has `patch` verbs of the `daemonsets` resource and delete verb of the pods resource ([clusterrole.yaml](https://github.com/kubereboot/charts/blob/main/charts/kured/templates/clusterrole.yaml)) and [role.yaml](https://github.com/kubereboot/charts/blob/main/charts/kured/templates/role.yaml)). However, after reading the source code of [kured](https://github.com/kubereboot/kured), I didn't find any Kubernetes API usages that require these permissions. Therefore, for security reasons, I suggest checking these permissions to determine if they are truly unnecessary. If they are, the issue should be fixed by removing the unnecessary permission or or other feasible methods.

**Comment by evrardjp** [comment]
Hello.

Wrong repository: please address this to https://github.com/kubereboot/kured. 
In your case it's necessary for ds lock.
