### ISSUE TITLE
Publish helm chart also as an OCI package (e.g. on GHCR registry)

### ISSUE THREAD

**Issue by nlamirault** [kubereboot/charts#88]
Could you push the packaged Helm chart also on ghcr.io, so we can pull/install the helm chart like this:

```
helm install kured oci://ghcr.io/kubereboot/charts --version x.y.z
```

**Comment by mkilchhofer** [comment]
I implemented this already. Charts arrive here: https://github.com/kubereboot/charts/pkgs/container/charts%2Fkured

Xref:
- https://github.com/kubereboot/charts/pull/75

**Comment by nlamirault** [comment]
Sorry for noise. Tks
