### ISSUE TITLE
Feature: Use of Apprise for notifications

### ISSUE THREAD

**Issue by steled** [kubereboot/charts#91]
Hi,

it seems that shoutrrr is not very well [updated](https://github.com/containrrr/shoutrrr/issues/450) (last release from Aug 20, 2023).
I had a look at [Apprise](https://github.com/caronc/apprise) which seem to be (currently) more active (last release Sep 2, 2024).

There is also a GUI interface which can be used [apprise-api](https://github.com/caronc/apprise-api).

Is it possible to use/implement Apprise instead of shoutrrr?

**Comment by steled** [comment]
Currently I build sosmething like a workaround, I'm deploying Apprise in the cluster (wrote some manifests that can be found [here](https://github.com/caronc/apprise-api/issues/212#issue-2608238700)) and using the shoutrrr generic webhook, config can be found [here](https://github.com/caronc/apprise/issues/1229#issuecomment-2432124621).

But this doesn't feel very great.

**Comment by evrardjp** [comment]
First, this is wrongly classified: If you want to change kured's behaviour, please file an issue on github.com/kubereboot/kured. 
Second, what's the issue with shoutrrr? 
Third, apprise does not have a golang sdk, correct?
